# Generated by Django 3.2.3 on 2021-06-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
